image: ghcr.io/vvv-school/gitpod:latest
ports:
- port: 6080
  onOpen: notify
- port: 10000-20000
  onOpen: ignore
workspaceLocation: "."
tasks:
- init: |
    mkdir -p /workspace/datasets && cd /workspace/datasets
    wget http://www.icub.org/download/software/datasetplayer-demo/testData_20120803_095402.zip
    unzip testData_20120803_095402.zip
    rm testData_20120803_095402.zip
- command: start-vnc-session.sh
- command: gp ports await 6080 && gp preview $(gp url 6080)
